name = "suk"
avatar = "images/profile.png" # Avatar image. Default to "images/profile.webp".
bio = "CyberSecurity newbie"
# company = 'High School'
# company = '<a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>'
location = "Japan"
# alternatives:
# location = "<a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>"
# location = "<a href='https://www.google.com/maps/search/Earth'>Earth</a>"
# about = "https://domain.tld" # The external about page. The internal about page will be used if not set.

[params]
  # layout = ""
  layout = "compact"

[social]
  #email = ""
  #facebook = "yourfacebookusername"
  github = "0xsuk"
  twitter = "0xsuk"
  #linkedin = "yourlinkedinusername"
